name: Node.js CI

on:
  push:
    branches: [ main, Ci-attempt-2 ]
  pull_request:
    branches: [ main, Ci-attempt-2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
          cd app/expressjs-backend
          echo "${{ secrets.ENV_FILE }}" > .env
          npm ci
          npm test -- --coverage

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

      - run: |
          cd app/react-frontend
          npm ci

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ListTogether'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2E6D4D7A14D3462298AA8697342AF117 }}
          package: .
